[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "embedapi"
version = "0.0.12"
dependencies = [
    "requests",
    "numpy",
    "more_itertools",
    "openai",
]

[tool.poetry]
name = "embedapi"
