[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "embedapi"
version = "0.0.1"
dependencies = [
    "requests",
    "numpy",
    "more_itertools",
    "openai",
    "fastapi",
    "sentence_transformers",
    "uvicorn[standard]",
]
